# TUGAS PRAKTIKUM METODE NUMERIK

**Achmad Rizki Baehaki**

**2106725066**

**KELAS D**

#**Nomor 1**

Diberikan SPL sebagai berikut:

  $ 2x_1 − x_2 + x_3 = −1 $,

  $ 2x_1 + 2x_2 + 2x_3 = 4 $,

  $ −x_1 − x_2 + 2x_3 = −5$

  Dengan $x^0 = 0 $, dan toleransi $10^{-5}$

  a. Gunakan metode Jacobi dan Gauss-Seidel untuk mengaproksimasi solusi
SPL di atas.

  b. Berapa iterasi yang diperlukan untuk masing-masing metode sampai
memenuhi batas toleransi?

  c. Apakah terdapat perbedaan jumlah iterasi di antara metode Jacobi dan
Gauss-Seidel? Berikan pendapatmu

  d. Jika $x^0$ = [1,1,1], apakah didapat hasil aproksimasi yang berbeda? Berikan
pendapatmu

# **Kode Penyelesaian SPL nomor 1**

# Metode Jacobi dengan tebakan awal $x^0 = [0,0,0]$

In [ ]:
import numpy as np
from tabulate import tabulate

augmented_matrix = np.array(eval(input('Masukkan augmented matrix yang akan diselesaikan: ')))        #masukkan augmented matriks dari SPL
initial_solution = np.array(eval(input('Masukkan tebakan solusi awal: ')), dtype=float)               #masukkan tebakan awal solusi
tolerance = eval(input('Masukkan toleransi: '))                                                       #masukkan toleransi
A = np.array(augmented_matrix)                                                                        #mengubah list menjadi array matriks

def Jacob(matrix,initial,tol):                                                                        #pendefinisian Metode Jacob
  k = np.shape(matrix)[0]                                                                             #menentukan ukuran baris dan kolom matriks
  x0 = initial
  x = x0.copy()                                                                                       #agar x tidak ikut berubah
  for i in range(k):
    b = matrix[i,k]                                                                                   #konstanta spl
    for j in range(k):
      if j != i:#pendefinisian Metode Jacob
        b -= matrix[i,j]*x0[j]                                                                        #rumus utama Metode Jacob
    x[i]= b/matrix[i,i]
  banyak_iterasi = 1                                                                                  #pendefinisian iterasi awal yaitu dimulai dari 1
  table = []
  while np.linalg.norm(x-x0,np.inf)>=tol and banyak_iterasi < 4000 :                                  #penyetop error mutlak
    x0 = x #definisikan x0 sebagai x(n-1)
    x = x0.copy()                                                                                     #definisikan x sebagai x(n), tetapi awalnya disamakan dengan x0
    table.append([banyak_iterasi,x[0],x[1],x[2]])                                                     #masukkan elemen-elemen pada langkah iterasi ke sebuah list
    banyak_iterasi +=1
    for i in range(k):
      b = matrix[i,k]
      for j in range(k):
        if j!=i:
          b-=matrix[i,j]*x0[j]
      x[i]=b/matrix[i,i]

  table.append([banyak_iterasi,x[0],x[1],x[2]])                                                       #memasukkan hasil aproksimasi pada langkah akhir iterasi dalam tabel
  judul_label = ['Iterasi ke-','x1','x2','x3']
  print(tabulate(table, headers = judul_label , tablefmt = 'pretty', numalign = "center", stralign = "center", floatfmt = ".8f")) #mencetak tabel dari iterasi penyelesaian SPL
  print('Aproksimasi solusi SPL dengan Metode Jacobi adalah: ')
  return x

print(A)
print(Jacob(augmented_matrix,initial_solution,tolerance))                                                #mencetak aproksimasi penyelesaian SPL

Masukkan augmented matrix yang akan diselesaikan: [[2,-1,0,3],[-1,2,-1,-3],[0,-1,2,5]]
Masukkan tebakan solusi awal: [0,0,0]
Masukkan toleransi: 10**-3
[[ 2 -1  0  3]
 [-1  2 -1 -3]
 [ 0 -1  2  5]]
+-------------+----------------+----------------+----------------+
| Iterasi ke- |       x1       |       x2       |       x3       |
+-------------+----------------+----------------+----------------+
|      1      |      1.5       |      -1.5      |      2.5       |
|      2      |      0.75      |      0.5       |      1.75      |
|      3      |      1.75      |     -0.25      |      2.75      |
|      4      |     1.375      |      0.75      |     2.375      |
|      5      |     1.875      |     0.375      |     2.875      |
|      6      |     1.6875     |     0.875      |     2.6875     |
|      7      |     1.9375     |     0.6875     |     2.9375     |
|      8      |    1.84375     |     0.9375     |    2.84375     |
|      9      |    1.96875     |    0.84375     |    2.96875     

# Metode Gauss Seidel dengan tebakan awal $x^0 = [0,0,0]$

In [ ]:
import numpy as np                                                                                    #import package
from tabulate import tabulate

augmented_matrix = np.array(eval(input('Masukkan augmented matrix yang akan diselesaikan: ')))        #masukkan augmented matriks dari SPL
initial_solution = np.array(eval(input('Masukkan tebakan solusi awal: ')), dtype=float)               #masukkan tebakan awal dari solusi spl
tolerance = eval(input('Masukkan toleransi: '))                                                       #Mengubah list menjadi array matriks
A = np.array(augmented_matrix)

def GaussSeidel(matrix,initial,tol):                                                                  #pendefinisian Metode Gauss Seidel
  k = np.shape(matrix)[0]                                                                             # menentukan ukuran baris dan kolom dari matriks (k
  x0 = initial
  x = x0.copy()                                                                                       #agar x tidak berubah
  for i in range(k):
    b = matrix[i,k]                                                                                   #konstanta dari SPL
    for j in range(k):
      if j != i:
        if j<i:
          b -= matrix[i,j]*x[j]
        else:
          b -= matrix[i,j]*x0[j]                                                                      #rumus Metode Gauss Seidel
    x[i]= b/matrix[i,i]
  banyak_iterasi = 1                                                                                  #pendefinisian iterasi dimulai dari 1
  tabel = []
  while np.linalg.norm(x-x0,np.inf)>=tol and banyak_iterasi < 4000 :                                  # penyetop error mutlak
    x0 = x                                                                                            #definisikan x0 sebagai x(n-1), dengan n banyak iterasi
    x = x0.copy()
    isi_label = [banyak_iterasi,x[0],x[1],x[2]]                                                       #pendefinisian x sebagai x(n), dengan n banyak iterasi
    tabel.append(isi_label)                                                                           #memasukkan elemen-elemen pada langkah iterasi ke sebuah list
    banyak_iterasi +=1
    for i in range(k):
      b = matrix[i,k]
      for j in range(k):
        if j!=i:
          if j<i:
            b -= matrix[i,j]*x[j]
          else:
           b -= matrix[i,j]*x0[j]                                                                     #rumus Metode Gauss Seidel
      x[i]= b/matrix[i,i]

  isi_label = [banyak_iterasi,x[0],x[1],x[2]]
  tabel.append(isi_label)                                                                             #memasukkan hasil aproksimasi pada langkah akhir iterasi dalam tabel
  judul_label = ['Iterasi ke-', 'x1', 'x2', 'x3']
  print(tabulate(tabel, headers = judul_label, tablefmt = 'pretty', numalign = "center", stralign = "center", floatfmt = ".8f")) #menampilkan tabel iterasi aproksimasi soluasi spl
  print('Aproksimasi solusi SPL dengan Metode Gauss Seidel adalah: ')                                 #mencetak aproksimasi solusi spl gauss seidel
  return x

print(A)                                                                                              #mencetak array matriks
print(GaussSeidel(augmented_matrix,initial_solution,tolerance))

Masukkan augmented matrix yang akan diselesaikan: [[2,-1,1,-1], [2,2,2,4],[-1,-1,2,-5]]
Masukkan tebakan solusi awal: [0,0,0]
Masukkan toleransi: 10**-5
[[ 2 -1  1 -1]
 [ 2  2  2  4]
 [-1 -1  2 -5]]
+-------------+--------------------+--------------------+---------------------+
| Iterasi ke- |         x1         |         x2         |         x3          |
+-------------+--------------------+--------------------+---------------------+
|      1      |        -0.5        |        2.5         |        -1.5         |
|      2      |        1.5         |        2.0         |        -0.75        |
|      3      |       0.875        |       1.875        |       -1.125        |
|      4      |        1.0         |       2.125        |       -0.9375       |
|      5      |      1.03125       |      1.90625       |      -1.03125       |
|      6      |      0.96875       |       2.0625       |      -0.984375      |
|      7      |     1.0234375      |     1.9609375      |     -1.0078125      |
|

# Metode Jacobi dengan tebakan awal $x^0 = [1,1,1]$

In [ ]:
import numpy as np
from tabulate import tabulate

augmented_matrix = np.array(eval(input('Masukkan augmented matrix yang akan diselesaikan: ')))        #masukkan augmented matriks dari SPL
initial_solution = np.array(eval(input('Masukkan tebakan solusi awal: ')), dtype=float)               #masukkan tebakan awal solusi
tolerance = eval(input('Masukkan toleransi: '))                                                       #masukkan toleransi
A = np.array(augmented_matrix)                                                                        #mengubah list menjadi array matriks

def Jacob(matrix,initial,tol):                                                                        #pendefinisian Metode Jacob
  k = np.shape(matrix)[0]                                                                             #menentukan ukuran baris dan kolom matriks
  x0 = initial
  x = x0.copy()                                                                                       #agar x tidak ikut berubah
  for i in range(k):
    b = matrix[i,k]                                                                                   #konstanta spl
    for j in range(k):
      if j != i:                                                                                      #pendefinisian Metode Jacobi
        b -= matrix[i,j]*x0[j]                                                                        #rumus utama Metode Jacob
    x[i]= b/matrix[i,i]
  banyak_iterasi = 1                                                                                  #pendefinisian iterasi awal yaitu dimulai dari 1
  table = []
  while np.linalg.norm(x-x0,np.inf)>=tol and banyak_iterasi < 4000 :                                  #penyetop error mutlak
    x0 = x                                                                                            #definisikan x0 sebagai x(n-1), dimana n banyak iterasi
    x = x0.copy()                                                                                     #definisikan x sebagai x(n), tetapi awalnya disamakan dengan x0
    table.append([banyak_iterasi,x[0],x[1],x[2]])                                                     #masukkan elemen-elemen pada langkah iterasi ke sebuah list
    banyak_iterasi +=1
    for i in range(k):
      b = matrix[i,k]
      for j in range(k):
        if j!=i:
          b-=matrix[i,j]*x0[j]
      x[i]=b/matrix[i,i]

  table.append([banyak_iterasi,x[0],x[1],x[2]])                                                       #memasukkan hasil aproksimasi pada langkah akhir iterasi dalam tabel
  judul_label = ['Iterasi ke-','x1','x2','x3']
  print(tabulate(table, headers = judul_label , tablefmt = 'pretty', numalign = "center", stralign = "center", floatfmt = ".8f")) #mencetak tabel dari iterasi penyelesaian SPL
  print('Aproksimasi solusi SPL dengan Metode Jacobi adalah: ')
  return x

print(A)
print(Jacob(augmented_matrix,initial_solution,tolerance))                                                #mencetak aproksimasi penyelesaian SPL

Masukkan augmented matrix yang akan diselesaikan: [[2,-1,1,-1], [2,2,2,4],[-1,-1,2,-5]]
Masukkan tebakan solusi awal: [1,1,1]
Masukkan toleransi: 10**-5
[[ 2 -1  1 -1]
 [ 2  2  2  4]
 [-1 -1  2 -5]]
+-------------+--------------------------+--------------------------+--------------------------+
| Iterasi ke- |            x1            |            x2            |            x3            |
+-------------+--------------------------+--------------------------+--------------------------+
|      1      |           -0.5           |           0.0            |           -1.5           |
|      2      |           0.25           |           4.0            |          -2.75           |
|      3      |          2.875           |           4.5            |          -0.375          |
|      4      |          1.9375          |           -0.5           |          1.1875          |
|      5      |         -1.34375         |          -1.125          |         -1.78125         |
|      6      |        -0

# Metode Gauss Seidel dengan tebakan awal $x^0 = [1,1,1]$

In [ ]:
import numpy as np                                                                                    #import package
from tabulate import tabulate

augmented_matrix = np.array(eval(input('Masukkan augmented matrix yang akan diselesaikan: ')))        #masukkan augmented matriks dari SPL
initial_solution = np.array(eval(input('Masukkan tebakan solusi awal: ')), dtype=float)               #masukkan tebakan awal dari solusi spl
tolerance = eval(input('Masukkan toleransi: '))                                                       #Mengubah list menjadi array matriks
A = np.array(augmented_matrix)

def GaussSeidel(matrix,initial,tol):                                                                  #pendefinisian Metode Gauss Seidel
  k = np.shape(matrix)[0]                                                                             # menentukan ukuran baris dan kolom dari matriks (k
  x0 = initial
  x = x0.copy()                                                                                       #agar x tidak berubah
  for i in range(k):
    b = matrix[i,k]                                                                                   #konstanta dari SPL
    for j in range(k):
      if j != i:
        if j<i:
          b -= matrix[i,j]*x[j]
        else:
          b -= matrix[i,j]*x0[j]                                                                      #rumus Metode Gauss Seidel
    x[i]= b/matrix[i,i]
  banyak_iterasi = 1                                                                                  #pendefinisian iterasi dimulai dari 1
  tabel = []
  while np.linalg.norm(x-x0,np.inf)>=tol and banyak_iterasi < 4000 :                                  # penyetop error mutlak
    x0 = x                                                                                            #definisikan x0 sebagai x(n-1), dengan n banyak iterasi
    x = x0.copy()
    isi_label = [banyak_iterasi,x[0],x[1],x[2]]                                                       #pendefinisian x sebagai x(n), dengan n banyak iterasi
    tabel.append(isi_label)                                                                           #memasukkan elemen-elemen pada langkah iterasi ke sebuah list
    banyak_iterasi +=1
    for i in range(k):
      b = matrix[i,k]
      for j in range(k):
        if j!=i:
          if j<i:
            b -= matrix[i,j]*x[j]
          else:
           b -= matrix[i,j]*x0[j]                                                                     #rumus Metode Gauss Seidel
      x[i]= b/matrix[i,i]

  isi_label = [banyak_iterasi,x[0],x[1],x[2]]
  tabel.append(isi_label)                                                                             #memasukkan hasil aproksimasi pada langkah akhir iterasi dalam tabel
  judul_label = ['Iterasi ke-', 'x1', 'x2', 'x3']
  print(tabulate(tabel, headers = judul_label, tablefmt = 'pretty', numalign = "center", stralign = "center", floatfmt = ".8f")) #menampilkan tabel iterasi aproksimasi soluasi spl
  print('Aproksimasi solusi SPL dengan Metode Gauss Seidel adalah: ')                                 #mencetak aproksimasi solusi spl gauss seidel
  return x

print(A)                                                                                              #mencetak array matriks
print(GaussSeidel(augmented_matrix,initial_solution,tolerance))

Masukkan augmented matrix yang akan diselesaikan: [[2,-1,1,-1], [2,2,2,4],[-1,-1,2,-5]]
Masukkan tebakan solusi awal: [1,1,1]
Masukkan toleransi: 10**-5
[[ 2 -1  1 -1]
 [ 2  2  2  4]
 [-1 -1  2 -5]]
+-------------+--------------------+--------------------+---------------------+
| Iterasi ke- |         x1         |         x2         |         x3          |
+-------------+--------------------+--------------------+---------------------+
|      1      |        -0.5        |        1.5         |        -2.0         |
|      2      |        1.25        |        2.75        |        -0.5         |
|      3      |       1.125        |       1.375        |        -1.25        |
|      4      |       0.8125       |       2.4375       |       -0.875        |
|      5      |      1.15625       |      1.71875       |       -1.0625       |
|      6      |      0.890625      |      2.171875      |      -0.96875       |
|      7      |     1.0703125      |     1.8984375      |      -1.015625      |
|

##**Jawaban nomor 1**

a. seperti running kode yang diatas

b. Banyak iterasi dari Metode Jacobi sebenarnya tak terbatas/ tidak diketahui jumlah maksimalnya jika tidak diberi pembatasan. Hal tersebut mengindikasikan bahwasannya hasil solusi SPL metode Jacobi menjauhi hasil sebenarnya(divergen) untuk memenuhi toleransi solusi $10^-5$. Sedangkan untuk metode Gauss Seidel hanya membutuhkan 23 iterasi untuk menghasilkasan solusi SPL dengan toleransi $10^-5$

c. Iya, terdapat perbedaan iterasi untuk memenuhi toleransi $10^-5$, dimana dalam kode diatas Metode Jacobi membutuhkan lebih dari 4000 iterasi (infinity) untuk menghasilkan solusi SPL dengan toleransi tersebut, sedangkan Metode Gauss Seidel hanya membutuhkan 23 iterasi agar menghasilkan solusi dengan toleransi $10^-5$

d. Berdasarkan hasil kode diatas,

**terdapat perbedaan hasil iterasi ke-4000 untuk metode Jacobi tebakan awal

$x_0 = [0,0,0]$ yang mana menghasilkan $[x_1,x_2,x_3] = [-3.96439817e+193, -1.58575927e+194, 3.96439817e+193]$

dengan tebakan awal

$x_0 = [1,1,1]$ yang mana menghasilkan
$[x_1,x_2,x_3] = [ 3.96439817e+193, -1.05717284e+194, 9.25026239e+193]$

untuk tebakan $x_0 = [1,1,1]$ hasil iterasi lebih cepat menjauhi solusi dibandingkan dengan tebakan $x_0 = [0,0,0]$


**hasil relatif sama untuk metode Gauss Seidel dengan tebakan

$x_0 = [0,0,0]$ yang mana menghasilkan $[x_1,x_2,x_3] = [ 1.00000226 , 1.9999975 ,-1.00000012]$ untuk iterasi ke 23
dan

$x_0 = [1,1,1]$ yang mana menghasilkan $[x_1,x_2,x_3] = [ 0.99999744 , 2.0000028  ,-0.99999988]$ untuk iterasi ke 24

#**Nomor 2**

Bandingkan iterasi Jacobi dan Gauss-Seidel dalam menyelesaikan SPL berikut

$ x_1 + 4x_2 + x_3 + 2x_4 = 8$

$x_1 + 4x_2 + x_3 + x_4 = 7$

$x_1 + 2x_2 + 3x_3 + 2x_4 = 8$

$x_1 + x_2 + 7x_3 + 4x_4 = 14 $

Gunakan $x^0 = [1,1,1,1]$ dan toleransi $10^{-4}$, Jelaskan jawabanmu!

# **Kode Penyelesaian SPL Nomor 2**

# Metode Jacobi

In [ ]:
import numpy as np
from tabulate import tabulate

augmented_matrix = np.array(eval(input('Masukkan augmented matrix yang akan diselesaikan: ')))        #masukkan augmented matriks dari SPL
initial_solution = np.array(eval(input('Masukkan tebakan solusi awal: ')), dtype=float)               #masukkan tebakan awal solusi
tolerance = eval(input('Masukkan toleransi: '))                                                       #masukkan toleransi
A = np.array(augmented_matrix)                                                                        #mengubah list menjadi array matriks

def Jacob(matrix,initial,tol):                                                                        #pendefinisian Metode Jacob
  k = np.shape(matrix)[0]                                                                             #menentukan ukuran baris dan kolom matriks
  x0 = initial
  x = x0.copy()                                                                                       #agar x tidak ikut berubah
  for i in range(k):
    b = matrix[i,k]                                                                                   #konstanta spl
    for j in range(k):
      if j != i:                                                                                      #pendefinisian Metode Jacobi
        b -= matrix[i,j]*x0[j]                                                                        #rumus utama Metode Jacob
    x[i]= b/matrix[i,i]
  banyak_iterasi = 1                                                                                  #pendefinisian iterasi awal yaitu dimulai dari 1
  table = []
  while np.linalg.norm(x-x0,np.inf)>=tol and banyak_iterasi < 4000 :                                  #penyetop error mutlak
    x0 = x                                                                                            #definisikan x0 sebagai x(n-1), dimana n banyak iterasi
    x = x0.copy()                                                                                     #definisikan x sebagai x(n), tetapi awalnya disamakan dengan x0
    table.append([banyak_iterasi,x[0],x[1],x[2]])                                                     #masukkan elemen-elemen pada langkah iterasi ke sebuah list
    banyak_iterasi +=1
    for i in range(k):
      b = matrix[i,k]
      for j in range(k):
        if j!=i:
          b-=matrix[i,j]*x0[j]
      x[i]=b/matrix[i,i]

  table.append([banyak_iterasi,x[0],x[1],x[2]])                                                       #memasukkan hasil aproksimasi pada langkah akhir iterasi dalam tabel
  judul_label = ['Iterasi ke-','x1','x2','x3']
  print(tabulate(table, headers = judul_label , tablefmt = 'pretty', numalign = "center", stralign = "center", floatfmt = ".8f")) #mencetak tabel dari iterasi penyelesaian SPL
  print('Aproksimasi solusi SPL dengan Metode Jacobi adalah: ')
  return x

print(A)
print(Jacob(augmented_matrix,initial_solution,tolerance))                                                #mencetak aproksimasi penyelesaian SPL

Masukkan augmented matrix yang akan diselesaikan: [[1,4,1,2,8],[1,4,1,1,7],[1,2,3,2,8],[1,1,7,4,14]]
Masukkan tebakan solusi awal: [1,1,1,1]
Masukkan toleransi: 10**-4
[[ 1  4  1  2  8]
 [ 1  4  1  1  7]
 [ 1  2  3  2  8]
 [ 1  1  7  4 14]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:30: RuntimeWarning: overflow encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:30: RuntimeWarning: overflow encountered in multiply


+-------------+--------------------------+--------------------------+--------------------------+
| Iterasi ke- |            x1            |            x2            |            x3            |
+-------------+--------------------------+--------------------------+--------------------------+
|      1      |           1.0            |           1.0            |           1.0            |
|      2      |           0.5            |          0.9375          |    0.8333333333333334    |
|      3      |    0.9166666666666665    |    1.1041666666666667    |    1.0416666666666667    |
|      4      |    -0.822916666666667    |    0.8398437500000001    |    0.5034722222222223    |
|      5      |    1.7934027777777772    |    1.5368923611111112    |    1.5998263888888893    |
|      6      |    -4.976779513888889    |   0.24801974826388906    |   -0.6988570601851848    |
|      7      |    7.971317997685185     |    3.2019766348379632    |    4.248426649305556     |
|      8      |   -20.86671278

# Metode Gauss Seidel

In [ ]:
import numpy as np                                                                                    #import package
from tabulate import tabulate

augmented_matrix = np.array(eval(input('Masukkan augmented matrix yang akan diselesaikan: ')))        #masukkan augmented matriks dari SPL
initial_solution = np.array(eval(input('Masukkan tebakan solusi awal: ')), dtype=float)               #masukkan tebakan awal dari solusi spl
tolerance = eval(input('Masukkan toleransi: '))                                                       #Mengubah list menjadi array matriks
A = np.array(augmented_matrix)

def GaussSeidel(matrix,initial,tol):                                                                  #pendefinisian Metode Gauss Seidel
  k = np.shape(matrix)[0]                                                                             # menentukan ukuran baris dan kolom dari matriks (k
  x0 = initial
  x = x0.copy()                                                                                       #agar x tidak berubah
  for i in range(k):
    b = matrix[i,k]                                                                                   #konstanta dari SPL
    for j in range(k):
      if j != i:
        if j<i:
          b -= matrix[i,j]*x[j]
        else:
          b -= matrix[i,j]*x0[j]                                                                      #rumus Metode Gauss Seidel
    x[i]= b/matrix[i,i]
  banyak_iterasi = 1                                                                                  #pendefinisian iterasi dimulai dari 1
  tabel = []
  while np.linalg.norm(x-x0,np.inf)>=tol and banyak_iterasi < 4000 :                                  # penyetop error mutlak
    x0 = x                                                                                            #definisikan x0 sebagai x(n-1), dengan n banyak iterasi
    x = x0.copy()
    isi_label = [banyak_iterasi,x[0],x[1],x[2]]                                                       #pendefinisian x sebagai x(n), dengan n banyak iterasi
    tabel.append(isi_label)                                                                           #memasukkan elemen-elemen pada langkah iterasi ke sebuah list
    banyak_iterasi +=1
    for i in range(k):
      b = matrix[i,k]
      for j in range(k):
        if j!=i:
          if j<i:
            b -= matrix[i,j]*x[j]
          else:
           b -= matrix[i,j]*x0[j]                                                                     #rumus Metode Gauss Seidel
      x[i]= b/matrix[i,i]

  isi_label = [banyak_iterasi,x[0],x[1],x[2]]
  tabel.append(isi_label)                                                                             #memasukkan hasil aproksimasi pada langkah akhir iterasi dalam tabel
  judul_label = ['Iterasi ke-', 'x1', 'x2', 'x3']
  print(tabulate(tabel, headers = judul_label, tablefmt = 'pretty', numalign = "center", stralign = "center", floatfmt = ".8f")) #menampilkan tabel iterasi aproksimasi soluasi spl
  print('Aproksimasi solusi SPL dengan Metode Gauss Seidel adalah: ')                                 #mencetak aproksimasi solusi spl gauss seidel
  return x

print(A)                                                                                              #mencetak array matriks
print(GaussSeidel(augmented_matrix,initial_solution,tolerance))

Masukkan augmented matrix yang akan diselesaikan: [[1,4,1,2,8],[1,4,1,1,7],[1,2,3,2,8],[1,1,7,4,14]]
Masukkan tebakan solusi awal: [1,1,1,1]
Masukkan toleransi: 10**-4
[[ 1  4  1  2  8]
 [ 1  4  1  1  7]
 [ 1  2  3  2  8]
 [ 1  1  7  4 14]]
+-------------+-------------------------+-------------------------+-------------------------+
| Iterasi ke- |           x1            |           x2            |           x3            |
+-------------+-------------------------+-------------------------+-------------------------+
|      1      |           1.0           |           1.0           |           1.0           |
|      2      |           0.5           |         1.0625          |   0.9583333333333334    |
|      3      |  -0.07291666666666652   |   1.1705729166666665    |   0.9557291666666666    |
|      4      |   -0.7441406249999996   |     1.308837890625      |   1.0067816840277777    |
|      5      |   -1.4360487196180558   |   1.4580773247612846    |   1.1086595323350692    |
|      

**Jawaban**

Solusi SPL dari Metode Jacobi dan gauss Seidel memiliki iterasi tak terbatas untuk memenuhi toleransi $10^-4$, akan tetapi Metode Jacobi Lebih Cepat untuk menghasilkan solusi yang lebih besar daripada Gauss Seidel, hal tersebut dapat dilihat pada iterasi ke 957.