Nama : Achmad Rizki Baehaki

NPM : 2106725066

# **SOAL NOMOR 1**

Input matriks 4x5 dengan:

● Elemen baris pertama dan keempat adalah hasil random dengan
|aij|< 100, aij∈Z

● Baris kedua berisi 5 digit pertama NPM

● Baris ketiga berisi 5 digit terakhir NPM

Output yang dihasilkan berupa solusi SPL yang ada dengan menggunakan kedua strategi pivoting.
Jangan lupa untuk menampilkan langkah-langkahnya, ya!

**Bonus :**
1. Gunakan error handling jika SPL tidak memiliki solusi unik
2. Buatlah program yang dapat diulang

In [ ]:
import numpy as np

print("====Selamat Datang di Program Solusi Persamaan Linier====")

#Penjelasan Ulang dalam menjalankan program
Running = "Yes"
while Running == "Yes" or Running == "yes":
  NPM = input("Masukkan NPM Anda: ")
  matrix=[np.random.randint(-100,100, size=5),[NPM[0],NPM[1],NPM[2],NPM[3],NPM[4]],[NPM[5],NPM[6],NPM[7],NPM[8],NPM[9]],np.random.randint(-100,100, size=5)]#Pendefinisian matriks yang akan dioperasikan
  matrix_partial=np.array(matrix,dtype=float)#mengubah list menjadi array
  matrix_scaled=matrix_partial.copy()#penyalinan untuk 2 cara yang berbeda
  print("Matrix Augmented yang terbentuk adalah: ")
  print(matrix_partial)

  def PartialPivoting(matrix_partial):
    n = np.shape(matrix_partial)[0]   # ukuran baris dari matriks
    for i in range(n-1):
      below_pivot=abs(matrix_partial[i:,i])
      pivot_row=np.argmax(below_pivot) # elemen maksimum
      if matrix_partial[i, pivot_row+i]==0:
        return "Tidak ada solusi unik"
      else:
        matrix_partial[[pivot_row+i,i]]=matrix_partial[[i,pivot_row+i]]#pertukaran baris
      for j in range (i+1, n):#eleminasi gauss
        a=matrix_partial[j,i]/matrix_partial[i,i]
        matrix_partial[j]=matrix_partial[j]-a*matrix_partial[i]
      print("\n",matrix_partial)
    return matrix_partial

  def BackSubstitutionPartial(matrix_partial):
    n=np.shape(matrix_partial)[0]#mengambil ukuran baris dari matriks
    solution=np.zeros(n)
    solution[n-1]=matrix_partial[n-1,n]/matrix_partial[n-1,n-1]
    for i in range(n-2,-1,-1):
      for j in range(i+1,n):#banyaknya persamaan
        matrix_partial[i,n]-=matrix_partial[i,j]*solution[j]#array untuk menyimpan solusi
      solution[i]=matrix_partial[i,n]/matrix_partial[i,i]#substitusi balik
    return solution

  #Mencetak output dari partial pivoting
  print("\n\n---PARTIAL PIVOTING---\n")
  triangular_form=PartialPivoting(matrix_partial)
  print("\nTriangular matriksn akhir adalah :\n {0}".format(triangular_form))
  solution=BackSubstitutionPartial(triangular_form)
  print("\nSolusi dari partial pivoting ini adalah: ")
  A = np.array(solution)
  print(A)

  print("\n---------------------------------------------------------------------------\n")

  def ScaledPartialPivoting(matrix_scaled):
    n=np.shape(matrix_scaled)[0]#mengambil ukuran baris dari matriks
    s=np.array([max(abs(matrix_scaled[i,:n])) for i in range(n)])#menentukan skalar tiap kolom
    if 0 in s:
      return "Tidak ada solusi unik"

    for i in range(n-1):
      below_pivot=abs(matrix_scaled[i:,i])/s[i:]
      pivot_row=np.argmax(below_pivot)
      if matrix_scaled[i,pivot_row+i]=="0":
        return "Tidak ada solusi unik"
      else:
        matrix_scaled[[pivot_row+i,i]]=matrix_scaled[[i,pivot_row+i]]
        s[pivot_row+i],s[i]=s[i],s[pivot_row+i]
      for j in range(i+1,n):#eliminasi gauss
        a=matrix_scaled[j,i]/matrix_scaled[i,i]
        matrix_scaled[j]=matrix_scaled[j]-a*matrix_scaled[i]
      print("\n", matrix_scaled)
    return matrix_scaled

  def BackSubstitutionScaled(matrix_scaled):
    n=np.shape(matrix_scaled)[0]#mengambil ukuran baris dari matriks
    solution_scaled=np.zeros(n)
    solution_scaled[n-1]=matrix_scaled[n-1,n]/matrix_scaled[n-1,n-1]
    for i in range(n-2,-1,-1):
      for j in range(i+1,n):#banyaknya persamaan
        matrix_scaled[i,n]-=matrix_scaled[i,j]*solution_scaled[j]#array untuk menyimpan solusi
      solution_scaled[i]=matrix_scaled[i,n]/matrix_scaled[i,i]#substitusi balik
    return solution_scaled

      #Mencetak output dari scaled partial pivoting
  print("\n\n---SCALED PARTIAL PIVOTING---\n")
  triangular_form_scaled=ScaledPartialPivoting(matrix_scaled)
  print("\nTriangular matriksnya akhir adalah :\n {0}".format(triangular_form_scaled))
  solution_scaled=BackSubstitutionScaled(matrix_scaled)
  print("\nSolusi dari scaled partial pivoting ini adalah: ")
  B = np.array(solution_scaled)
  print(A)

  print('\n\n================================================')
  Running = str(input("Apakah anda mau menghitung ulang? (Yes/No): ")) #Pilihan untuk mecoba ulang program
  print('================================================\n\n')

if Running == "No"  or Running == "no" :                              #Program berhenti
  print("-Terimakasih-")






====Selamat Datang di Program Solusi Persamaan Linier====
Masukkan NPM Anda: 2106725066
Matrix Augmented yang terbentuk adalah: 
[[ 62.  76. -49. -47.  70.]
 [  2.   1.   0.   6.   7.]
 [  2.   5.   0.   6.   6.]
 [-37. -35.  46.  46. -78.]]


---PARTIAL PIVOTING---


 [[ 62.          76.         -49.         -47.          70.        ]
 [  0.          -1.4516129    1.58064516   7.51612903   4.74193548]
 [  0.           2.5483871    1.58064516   7.51612903   3.74193548]
 [  0.          10.35483871  16.75806452  17.9516129  -36.22580645]]

 [[ 6.20000000e+01  7.60000000e+01 -4.90000000e+01 -4.70000000e+01
   7.00000000e+01]
 [ 0.00000000e+00  1.03548387e+01  1.67580645e+01  1.79516129e+01
  -3.62258065e+01]
 [ 0.00000000e+00  0.00000000e+00 -2.54361371e+00  3.09813084e+00
   1.26573209e+01]
 [ 0.00000000e+00  2.22044605e-16  3.92990654e+00  1.00327103e+01
  -3.36448598e-01]]

 [[ 6.20000000e+01  7.60000000e+01 -4.90000000e+01 -4.70000000e+01
   7.00000000e+01]
 [ 0.00000000e+00  1.035483

**Menentukan Input dari NPM**

NPM = input("Masukkan NPM Anda: ")

**Mencetak Output berupa augmented matriks, proses, triangular matriks final, serta solusi persamaan dari 2 cara yang berbeda**

matrix=[np.random.randint(-100,100, size=5),[NPM[0],NPM[1],NPM[2],NPM[3],NPM[4]],[NPM[5],NPM[6],NPM[7],NPM[8],NPM[9]],np.random.randint(-100,100, size=5)]

print("Matrix Augmented yang terbentuk adalah: ")

print(matrix_partial)

print("\n\n---PARTIAL PIVOTING---\n")
  
triangular_form=PartialPivoting(matrix_partial)
  
print("\nTriangular matriksnya finalnya adalah :\n {0}".format(triangular_form))
  
solution=BackSubstitutionPartial(triangular_form)
  
print("\nSolusi dari partial ini adalah: ")

for i in range(len(solution)):
    
    print("x{0}={1}".format(i+1,solution[i]))



print("\n\n---SCALED PARTIAL PIVOTING---\n")
  
triangular_form_scaled=ScaledPartialPivoting(matrix_scaled)

print("\nTriangular matriksnya finalnya adalah :\n {0}".format(triangular_form_scaled))
  
solution_scaled=BackSubstitutionScaled(matrix_scaled)

print("\nSolusi dari partial ini adalah: ")

for i in range(len(solution_scaled)):
    
    print("x{0}={1}".format(i+1,solution_scaled[i]))

**Cara Kerja program ini adalah** input dari npm akan dimasukkan dalam sebuah matriks, matriks tersebut dijalankan sesuai def pilih (), sehingga menghasilkan output diatas. Program akan berulang sesuai dengan keinginan pengguna, sehingga pengguna memasukkan kembali nim, lalu proses akan berjalan lagi.

# **SOAL NOMOR 2**

Algoritmanya:
1. Definisikan matriks awal A sebagai matriks 3x3
2. Gunakan LU Factorization untuk mencari matriks segitiga bawah (L) dan segitiga
atas (U) dari matriks A
3. Definisikan matriks A1 sebagai A1 = L + U
4. Ulangi langkah 2 dan 3 sebanyak 10 kali sampai diperoleh matriks A10
5. Catatan: Matriks An = Ln−1 + Un−1 , contoh:

  Matriks A1 = L + U, di mana L dan U adalah hasil Faktorisasi LU matriks A

  Matriks A2 = L + U, di mana L dan U adalah hasil Faktorisasi LU matriks A1

  Matriks A3 = L + U, di mana L dan U adalah hasil Faktorisasi LU matriks A2

  . . .

  Matriks A10 = L + U, di mana L dan U adalah hasil Faktorisasi LU matriks A9

Hint: gunakan round() pada setiap elemen dari matriks L dan matriks U guna
menghindari angka yang terlalu rumit untuk dilakukan faktorisasi LU berikutnya

In [ ]:
import numpy as np

#menentukan matriks yang akan dimasukkan (input)
input_matrix = np.array(eval(input('Masukkan matriks A yang akan di faktorisasi: ')))

#Pendefinisian LU Factorization untuk mencari matriks segitiga bawah (L) dan segitiga atas (U) dari matriks A
def LUFactorization(input_matrix):
  m = np.shape(input_matrix)[0]                #menentukan ukuran baris
  L = np.identity(m)                           #L matriks mxm
  #operasi gauss
  for i in range(m):
    for j in range(i+1, m):
      a = input_matrix[j,i]/input_matrix[i,i]
      L[j,i] = a                                #elemen L_ji menjadi perkalian a = a_ji/a_ii
      input_matrix[j]= input_matrix[j]-a*input_matrix[i]
  return (L, input_matrix)

#menentukan perulangan rumus matriks dari A0 hingga menghasilkan A10
for a in range(10):
  L = LUFactorization(input_matrix)[0]          #nilai L pada LUFactorization
  U = LUFactorization(input_matrix)[1]          #nilai matrix pada LUFactorization

  matrix_row = np.shape(L)[0]
  matrix_column = np.shape(L)[1]

  for i in range(matrix_row):
    for j in range(matrix_column):
      L[i,j] = np.floor(L[i,j])
      U[i,j] = np.floor(U[i,j])
  #mencetak hasil (dalam looping)
  print("Matriks A{}-nya adalah \n{}".format(a,input_matrix))
  print("====================================")
  print("Faktorisasi LU dari matriks A{} adalah".format(a))
  print("Martiks L-nya adalah \n{}".format(L))
  print("Martiks U-nya adalah \n{}".format(U))
  input_matrix = L + U

#mencetak hasil (luar looping)
print("Matriks A10 adalah \n{}".format(input_matrix))
print("**************************")
print("Diperoleh Matriks A10 adalah \n{}".format(input_matrix))

Masukkan matriks yang akan di faktorisasi: [[7,3,6],[1,5,2],[6,2,7]]
Matriks A0-nya adalah 
[[7 3 6]
 [0 4 1]
 [0 0 1]]
Faktorisasi LU dari matriks A0 adalah
Martiks L-nya adalah 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Martiks U-nya adalah 
[[7 3 6]
 [0 4 1]
 [0 0 1]]
Matriks A1-nya adalah 
[[8. 3. 6.]
 [0. 5. 1.]
 [0. 0. 2.]]
Faktorisasi LU dari matriks A1 adalah
Martiks L-nya adalah 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Martiks U-nya adalah 
[[8. 3. 6.]
 [0. 5. 1.]
 [0. 0. 2.]]
Matriks A2-nya adalah 
[[9. 3. 6.]
 [0. 6. 1.]
 [0. 0. 3.]]
Faktorisasi LU dari matriks A2 adalah
Martiks L-nya adalah 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Martiks U-nya adalah 
[[9. 3. 6.]
 [0. 6. 1.]
 [0. 0. 3.]]
Matriks A3-nya adalah 
[[10.  3.  6.]
 [ 0.  7.  1.]
 [ 0.  0.  4.]]
Faktorisasi LU dari matriks A3 adalah
Martiks L-nya adalah 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Martiks U-nya adalah 
[[10.  3.  6.]
 [ 0.  7.  1.]
 [ 0.  0.  4.]]
Matriks A4-nya adalah 
[[11.  3.  6.]
 [ 0.  8.  1.]
 [ 0.  0.  5.]

**Menentukan matriks yang akan dimasukkan (Input)**

input_matrix = np.array(eval(input('Masukkan matriks A yang akan di faktorisasi: ')))

**Mencetak hasil Output berupa LU A0, A1, ....., A10**

print("Matriks A{}-nya adalah \n{}".format(a,input_matrix))

print("====================================")

print("Faktorisasi LU dari matriks A{} adalah".format(a))

print("Martiks L-nya adalah \n{}".format(L))

print("Martiks U-nya adalah \n{}".format(U))

input_matrix = L + U

print("Matriks A10 adalah \n{}".format(input_matrix))

print("**")

print("Diperoleh Matriks A10 adalah \n{}".format(input_matrix))

**Cara kerja program ini** adalah input matriks dijalankan sesuai def pilih() lalu outputnya dikembalikan dengan looping mengikuti fungsi def pilih () sebelumnya